# Generated by Django 5.1.6 on 2025-05-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
